const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE || '/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const requests=[];page.on('requestfailed',r=>requests.push(r.url()));
 const enable=async()=>{await page.locator('flt-semantics-placeholder').evaluate(e=>e.click());await page.getByRole('button',{name:'Agregar widget',exact:true}).waitFor();};
 try{
 await page.goto(process.env.PLANNER_URL || 'http://127.0.0.1:8765');await enable();
 await page.getByRole('button',{name:'Agregar widget',exact:true}).click();
 await page.getByRole('button',{name:/^Tareas Pendientes/}).click();
 await page.getByRole('button',{name:'Agregar tarea',exact:true}).click();
 await page.getByRole('textbox').fill('Leer 10 páginas');
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.getByRole('checkbox').click();
 await page.getByText('1 de 1 completadas',{exact:true}).waitFor();
 await page.reload();await enable();
 await page.getByText('Leer 10 páginas',{exact:true}).waitFor();
 assert.equal(await page.getByRole('checkbox').isChecked(),true);
 console.log('PASS task creation, completion and reload persistence');
 await page.getByRole('button',{name:'Plantillas',exact:true}).last().click();
 await page.getByRole('button',{name:/Día tranquilo/}).click();
 await page.screenshot({path:'/tmp/planner-desktop.png'});
 console.log('PASS template applied');
 await page.getByRole('button',{name:'Personalizar',exact:true}).click();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Exportar copia JSON',exact:true}).click();
 const download=await downloadPromise; await download.saveAs('/tmp/planner-backup.json');
 const backup=JSON.parse(require('node:fs').readFileSync('/tmp/planner-backup.json','utf8'));
 assert.equal(Object.values(backup.pages)[0].length,5);
 console.log('PASS backup export');
 await page.getByRole('button',{name:'Agregar widget',exact:true}).click();
 await page.getByRole('button',{name:/^Tareas Pendientes/}).click();
 await page.getByRole('button',{name:'Personalizar',exact:true}).click();
 const fileChooser=page.waitForEvent('filechooser');
 await page.getByRole('button',{name:'Restaurar copia JSON',exact:true}).click();
 await (await fileChooser).setFiles('/tmp/planner-backup.json');
 await page.getByRole('button',{name:'Restaurar',exact:true}).click();
 await page.getByText('Copia restaurada.',{exact:true}).last().waitFor();
 console.log('PASS backup import through file picker');
 const restored=await page.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('definitive_planner_v1'))));
 assert.equal(Object.values(restored.pages)[0].length,5);
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Abrir el menú de navegación',exact:true}).click();
 await page.getByRole('button',{name:'Vista general',exact:true}).click();
 await page.getByRole('textbox').click();
 await page.keyboard.type('zzzz-no-match');
 await page.getByText('Todavía no hay páginas que coincidan.',{exact:true}).waitFor();
 await page.keyboard.press('Control+A');
 await page.keyboard.type('Leer');
 await page.getByRole('button',{name:/Tareas[\s\S]*Nota[\s\S]*Agenda/}).waitFor();
 await page.screenshot({path:'/tmp/planner-phone.png'});
 assert.deepEqual(errors,[]);
 assert.deepEqual(requests,[]);
 console.log('PASS mobile navigation/search, no failed requests or JavaScript exceptions');
 }catch(error){console.error('Visible app text:',await page.locator('body').innerText());await page.screenshot({path:'/tmp/planner-smoke-failure.png'});throw error;}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
